Update PROPOSTA.md
CoPaJE/CoPaJE pull request #10
Opened 2023-07-03 20:18 UTC by migmoroni

- Melhoria geral na legibilidade e organização do projeto, utilizando de capítulos e generalizações.
- Adicionado mais profissões na área de jogos permitidas ao MEI.
- Aumento de multa (de 500 a 5 mil) Ufir, por não cumprimento de alteração de classificação etária.
- Pequenas simplificações

2023-07-03 20:34 UTC, tolstenko requested changes

2023-07-03 20:34 UTC, tolstenko commented on PROPOSTA.md
> +## Para aprovação de mudanças nesta proposta, seguimos as seguintes normas:
move essa parte pro arquivo https://github.com/CoPaJE/CoPaJE/blob/main/CONTRIBUTING.md

2023-07-03 20:42 UTC, migmoroni commented on PROPOSTA.md
> +## Para aprovação de mudanças nesta proposta, seguimos as seguintes normas:
Retirado esta parte do texto.

2023-07-05 14:03 UTC, tolstenko commented
LGTM. 

Extras:

Se vc nao fizer isso ou se outra pessoa nao se pronunciar como algo bloqueante, tah td bem por mim e eu farei as seguntes mudancas:

Designer eh um termo amplo e seria interessante deixar isso future-proof. Todos as seguintes posicoes sao Game designers. Entao seria interessate categorizar em termo amplo e depois especificar.
- Game designer eh o generalista dentro os designers que faz de tudo um pouco. A definicao dele deveria ser a tipificacao padrao.
- User Interface, User Experience - Nunca unam os dois pq isso vai dar problema. Sao coisos completamente diferentes. UI cria interface, UX cria a experiencia da navegacao. Eh a msm coisa que vc pegar o cara que faz modelo 3d e colocar como o msm cara que faz animacao do modelo 3d. Podem ser a msm pessoa, mas geralmente em AAA nao sao.
- Narrative Designer ou Roteirista. Ele eh designer tbm.
- Sound Designer - Eh o cara que cola e faz funcionar os audios, muscicas, efeitos sonoros etc.
- Temos tambem varios outros tipos de designers tais como economia, gampplay

Sobre developer, eu diria que ele eh o generalista de diversas outras areas. Um developer ou desenvolvedor eh o cara que programa e escreve codigo. Dentro dele, tambem entraria arquitetos de software e sistemas. Aqui vai uma lista simples so p vc ver que se vc quebrar em seguranca, vc tem q quebrar em outras areas tbm. Networking, Seguranca, Gameplay, Editor, Tools, Platform... e uma infinidade de outros

Acho q vale a pena tbm quebrar em marketing, tbm pq marketing de games eh extremamente especifico e complexo. Eh totalmente diferente de fazer marketing de produtos fisico, de app, e tbm qq outra area. Marketing de games eh um monstro por si so.

Favor assistir os creditos de diablo iv para ter mais inspiracao sobre como criar generalizacao de grupos e como especializar classes de trabalho. https://www.youtube.com/watch?v=yDyOcF9Iel8

2023-07-05 14:20 UTC, Germano123 commented
LGTM.

2023-07-05 14:23 UTC, tolstenko approved these changes

2023-07-05 14:23 UTC, merged

2023-07-05 14:23 UTC, tolstenko commented
Aprovado com ressalvas

2023-07-05 18:58 UTC, migmoroni commented
@tolstenko No caso do Designer concordo com você. Tanto que especifiquei isso no caput:
- IX - Designer de jogos: a pessoa física que é responsável por projetar a jogabilidade, as mecânicas, os sistemas do jogo, os desafios, as regras, as fases e as interações que compõem a experiência, para jogos de entretenimento. Atua em um escopo amplo, permitindo cumprir todo ou parcial, o papel informado nos incisos II, III, IV, V e VI deste artigo.

Olhe ao final: Atua em um escopo amplo, permitindo cumprir todo ou parcial, o papel informado nos incisos II, III, IV, V e VI deste artigo.

Assim, especifiquei as profissões separadas, mas também, especifiquei a profissão geral, muito usada por pequenos desenvolvedores indie, que fazem um pouco de tudo e que é especificada no pedido dessa profissão a lista de MEI.