Conclusão de tasks
CoPaJE/CoPaJE pull request #2
Opened 2023-06-23 14:10 UTC by Germano123

1. Tutorial de como contribuir - CONTRIBUTING.md
2. Escrever filosofias e objetivos
3. Copiar a proposta e esboco de documento para o Repo
4. Templates para propostas de melhorias
5. Templates para issues

2023-06-25 21:22 UTC, tolstenko requested changes
diversos pedidos de mudanca em linha. olhe os comentarios que deixei em cada arquivo

2023-06-25 21:22 UTC, tolstenko commented on .github/ISSUE_TEMPLATE/problema.md
Favor unir problema com proposta. 
Motivo: 
- Um levantamento de problema sem uma possivel solucao eh um levantamento vazio.

2023-06-25 21:22 UTC, tolstenko commented on .github/ISSUE_TEMPLATE/proposta.md
Favor unir problema com proposta. 
Motivo: 
- Um levantamento de problema sem uma possivel solucao eh um levantamento vazio.

2023-06-25 21:22 UTC, tolstenko commented on CONTRIBUTING.md
1. Adicione video youtube ou mesmo um gif(preferencialmente) ensinando como propor melhorias.
1.1 mostre como propor mudancas via browser - forma mais facil
1.2 mostre como submeter uma issue
1.3 EXTRA - mostre como fazer via clone/push/merge - opcional
2. adicione links e badges do discord e grupo whatsapp

2023-06-25 21:22 UTC, tolstenko commented on README.md
1. O link esta com analytics e tags sem muito sentido. Limpe o link.
2. Nao somos comissao. Somos Conselho. Favor renomear.
3. Remova termos em primeira pessoa. "Compreendo"
4. CoPaJE eh masculino. "O Conselho"
5. Sobre filosofia, adicione conceitos de sermos descentralizados e distribuidos e o quanto isso dignifica a nossa questao e fortifica a pauta. Quando vairas empresas e pessoas propoem melhorias, elas estao nao apenas assinando que concordam, mas ativamente atuaram para melhoria e vao ficar para sempre no historico de colaboradores da proposta final.
6. Proposta nao esta condizente. Proposta deve dizer resumidamente pra que existimos. Acredito que essa parete inteira possa sumir, dado que descrevemos em objetivo
7. Objetivos. Quebrar em um objetivo primario e abstrato e varios secundarios mais concretos.
8. Adicione badges e shields para links comuns. https://shields.io/badges/discord
9. Logo no comeco do README.md tem que ter um link pra outro MD que eh exatamente o doc de uma nova PL que vamos construir em paralelo e em conjunto. Tem que ser um call to action pq a galera em peso vai entrar pra olhar exatamente o documento e nao essa landing page.

2023-06-26 16:11 UTC, Germano123 commented on .github/ISSUE_TEMPLATE/problema.md
Na verdade, problema e proposta devem ser coisas separadas. Talvez os nomes não tenham ficados claros, nem suas justificativas de criações.

**Problema** é qualquer impedimento que possa se mostrar desvantagem pra continuarmos nosso trabalho ou continuar andando com nossas propostas.

**Proposta** é referente à quaisquer alterações e/ou adições que podem ser aplicadas no PL que estamos revisando.

2023-06-26 16:12 UTC, Germano123 commented on CONTRIBUTING.md
Vou adicionar isso novamente ao documento na parte de TODO e fazer isso conforme novas tasks forem sendo resolvidas.

2023-06-26 16:40 UTC, Germano123 commented on README.md
1. Resolvido - Removido analytics.
2. Resolvido - Alterado.
3. Resolvido - Alterado.
4. Resolvido - Alterado.
5. Resolvido - Alterado campo de transparência para descentralização.
6. Resolvido - Alterado campo de Proposta para Atuação para demonstrar primeiros passos.
7. Resolvido - Adicionado quebra de objetivos.
8. Pedido repetido em outro comentário. Desconsiderado por ser resolvido em outro caso.
9. Será adicionado como task na seção de TODOs como revisão do README - "adição do link da proposta".

2023-06-26 18:19 UTC, Germano123 commented on .github/ISSUE_TEMPLATE/proposta.md
Vou marcar essa como resolved porque está sendo debatida na outra issue.

2023-06-26 18:21 UTC, tolstenko commented on .github/ISSUE_TEMPLATE/problema.md
Renomeie entao esse arquivo de proposta para "proposta de alteracao", "merge request", "pull request" ou mesmo algo similar. Pois aqui consta como "PROBLEMA.md".
Na descricao tem 3 areas que ja vao estar dentro do MR/PR: antes, depois e descricao. Entao se vc renomear para ser o padrao de merge/pull request vai caber bem.
Creio que esse tipo de issue seria basicamente e merge/pull request.

2023-06-26 18:21 UTC, tolstenko commented on .github/ISSUE_TEMPLATE/proposta.md
1. Preste atencao que o arquivo tem nome de proposta e o texto tem escrito problema.
2. Para desambiguidade, favor renomear "problema" para "bloqueio" ou mesmo "desafio". Termo "problema" aqui esta muito aberto, sem falar que existem diferentes tipos de problemas que devem ser tratados de maneira diferente. Se vc quer se referir a uma issue geral. favor se referir a templates como esses para se inspirar e ser mais preciso. https://github.com/Josee9988/project-template/tree/master/.github/ISSUE_TEMPLATE

2023-06-26 18:21 UTC, tolstenko commented on CONTRIBUTING.md
LGTM

2023-06-26 18:21 UTC, tolstenko commented on README.md
LGTM

2023-06-26 18:25 UTC, Germano123 commented on .github/ISSUE_TEMPLATE/problema.md
Esse template na verdade deveria se comportar como um template pra ser debate com a comunidade antes de virar um MR/PR. Uma ideia para ser adicionado ao documento de proposta de lei, mas que antes pudesse ser debatido. Imagina como se fosse um request-for-comments RFC da comunidade Awesome GameDev Guild.

2023-06-26 18:33 UTC, Germano123 commented on .github/ISSUE_TEMPLATE/proposta.md
Alterado.

2023-06-26 18:33 UTC, Germano123 commented on .github/ISSUE_TEMPLATE/problema.md
Renomeação de arquivo feita.

2023-06-26 19:02 UTC, merged